// Modelos de base de conhecimento por nicho, usados no onboarding
// (/bem-vindo) pra pré-preencher a base de conhecimento do tenant assim
// que ele escolhe o tipo de negócio. Fatos genéricos e típicos do
// segmento — a dona só ajusta valores, horários e o que não se aplica.
export type Segmento = {
  id: string;
  nome: string;
  descricao: string;
  baseConhecimento: string[];
};

export const SEGMENTOS: Segmento[] = [
  {
    id: "salao-beleza",
    nome: "Salão de beleza",
    descricao: "Cabelo, unha, estética capilar",
    baseConhecimento: [
      "Corte feminino custa R$ 80 a R$ 150 dependendo do comprimento do cabelo, e leva de 40 a 60 minutos — ajuste pro preço real do salão.",
      "Escova custa R$ 60 a R$ 90 e leva cerca de 40 minutos.",
      "Coloração completa custa a partir de R$ 180, leva de 2 a 3 horas, e é recomendável reservar com antecedência.",
      "Luzes/mechas custam a partir de R$ 250 e levam de 2 a 4 horas dependendo da técnica.",
      "Manicure e pedicure custam R$ 45 cada, ou R$ 80 o combo, levando cerca de 1 hora.",
      "Escova progressiva/alisamento custa a partir de R$ 220 e leva de 2 a 3 horas.",
      "Agendamentos podem ser feitos com até 30 dias de antecedência.",
      "Cancelamento sem custo até 3 horas antes do horário marcado; depois disso pode ser cobrada taxa de 50% do serviço.",
      "Aceitamos pagamento via Pix, cartão de crédito/débito e dinheiro.",
      "Clientes atrasadas em mais de 15 minutos podem ter o horário remarcado, dependendo da agenda do dia.",
      "Recomendamos chegar 10 minutos antes do horário marcado.",
      "Pacotes de manutenção mensal (corte + escova) saem com desconto — perguntar sobre planos de fidelidade.",
      "Fazemos avaliação gratuita antes de serviços químicos (coloração, alisamento) pra avaliar o estado do cabelo.",
      "Se a cliente não souber qual serviço quer, pergunte o objetivo (mudar o visual, manter, ocasião especial) antes de sugerir.",
      "Em caso de alergia a produtos químicos, sempre perguntar sobre histórico antes de agendar coloração ou alisamento.",
    ],
  },
  {
    id: "barbearia",
    nome: "Barbearia",
    descricao: "Corte, barba, cuidados masculinos",
    baseConhecimento: [
      "Corte masculino custa R$ 45 a R$ 70 e leva cerca de 30 minutos.",
      "Barba (aparar e desenhar) custa R$ 35 a R$ 50 e leva de 20 a 30 minutos.",
      "Combo corte + barba custa R$ 70 a R$ 100 e leva cerca de 50 minutos.",
      "Sobrancelha (pezinho/navalhado) custa R$ 20 a R$ 30.",
      "Corte infantil custa R$ 35 a R$ 50.",
      "Agendamento pode ser feito pra até 30 dias à frente, com horários de manhã e tarde.",
      "Cancelamento gratuito até 1 hora antes; falta sem aviso pode gerar cobrança de reserva na próxima vez.",
      "Aceitamos Pix, cartão e dinheiro.",
      "Cliente sem hora marcada pode aguardar na fila conforme disponibilidade do dia.",
      "Assinatura mensal (corte ilimitado ou um número fixo de cortes por mês) costuma sair mais em conta — perguntar se o cliente tem interesse.",
      "Produtos de finalização (pomada, óleo de barba) também são vendidos no balcão.",
      "Em datas de alta demanda (véspera de feriado, fim de semana), recomendamos agendar com mais antecedência.",
      "Se o cliente pedir um corte com nome específico (undercut, degradê, social), confirme o número da máquina antes de agendar, caso ele saiba.",
      "Horário de pico costuma ser sábado de manhã — sugerir horários alternativos se a agenda estiver cheia.",
    ],
  },
  {
    id: "clinica-estetica",
    nome: "Clínica de estética",
    descricao: "Procedimentos faciais e corporais",
    baseConhecimento: [
      "Limpeza de pele profunda custa R$ 150 a R$ 250 e leva cerca de 1 hora.",
      "Sessão de drenagem linfática custa R$ 120 a R$ 180 e leva 50 minutos.",
      "Botox (toxina botulínica) custa a partir de R$ 800 por região, com resultado em até 15 dias e duração média de 4 a 6 meses.",
      "Preenchimento facial (ácido hialurônico) custa a partir de R$ 1.200 por seringa.",
      "Sessão de peeling químico custa R$ 200 a R$ 350, dependendo da profundidade.",
      "Depilação a laser é vendida em pacote de 6 a 10 sessões, com preço variando por região do corpo — consultar tabela específica.",
      "Massagem modeladora custa R$ 130 a R$ 200 por sessão; recomendamos pacote de 6 a 10 sessões pra resultado visível.",
      "Fazemos avaliação inicial gratuita pra procedimentos estéticos avançados (botox, preenchimento, laser).",
      "Procedimentos injetáveis (botox, preenchimento) exigem anamnese e são feitos só por profissional habilitado — nunca prometer resultado imediato exagerado.",
      "Cancelamento gratuito até 4 horas antes; remarcação sem custo com aviso prévio.",
      "Aceitamos Pix, cartão (parcelamos procedimentos acima de R$ 500) e dinheiro.",
      "Orientações de pós-procedimento (evitar sol, não tocar no local) são enviadas por escrito após a sessão.",
      "Pacotes fechados (ex: 10 sessões de drenagem) têm desconto em relação ao preço avulso.",
      "Se o cliente perguntar sobre contraindicações (gravidez, alergias, medicamentos), sempre recomendar confirmar com a esteticista antes de fechar o agendamento.",
      "Promoções sazonais (verão, Dia das Mães) costumam ter condições especiais — perguntar se há campanha ativa antes de informar preço padrão.",
    ],
  },
  {
    id: "odontologia",
    nome: "Consultório de odontologia",
    descricao: "Clínica dentária",
    baseConhecimento: [
      "Consulta de avaliação/check-up custa R$ 100 a R$ 150 e leva cerca de 30 minutos.",
      "Limpeza (profilaxia) custa R$ 120 a R$ 180.",
      "Restauração (obturação) custa a partir de R$ 150 por dente, dependendo do tamanho da cárie.",
      "Clareamento dental custa a partir de R$ 600 (no consultório) ou R$ 350 (caseiro supervisionado).",
      "Canal (tratamento endodôntico) custa a partir de R$ 500 por dente, geralmente em 2 a 3 sessões.",
      "Extração simples custa R$ 150 a R$ 300; extração de siso pode custar mais e exige avaliação prévia com raio-x.",
      "Aparelho ortodôntico tem avaliação inicial gratuita, com valor mensal a partir de R$ 150 dependendo do tipo (metálico, estético, invisível).",
      "Emergências odontológicas (dor forte, trauma, inchaço) têm prioridade e devem ser encaixadas no mesmo dia quando possível.",
      "Agendamentos podem ser feitos com até 60 dias de antecedência para tratamentos de rotina.",
      "Cancelamento gratuito até 24 horas antes; faltas recorrentes sem aviso podem exigir confirmação por telefone antes de novo agendamento.",
      "Aceitamos Pix, cartão (parcelamos tratamentos acima de R$ 400) e convênios odontológicos específicos — perguntar qual convênio o paciente tem.",
      "Antes de procedimentos cirúrgicos (extração, implante), é recomendável informar se o paciente toma anticoagulante ou tem alguma condição de saúde relevante.",
      "Implante dentário exige avaliação com raio-x e planejamento — não tem preço fechado sem consulta prévia.",
      "Se o paciente estiver com muita dor, oriente a procurar atendimento de urgência e, se possível, ofereça encaixe no mesmo dia.",
      "Consultas de retorno pós-procedimento costumam ser gratuitas dentro do período de garantia do tratamento.",
    ],
  },
  {
    id: "advocacia",
    nome: "Escritório de advocacia",
    descricao: "Consultoria e atuação jurídica",
    baseConhecimento: [
      "A primeira consulta de avaliação do caso é gratuita ou custa uma taxa simbólica de até R$ 100, dependendo da área — confirmar a política real do escritório.",
      "Áreas de atuação comuns: trabalhista, cível, família (divórcio/pensão), consumidor, criminal — informar apenas as que o escritório realmente atende.",
      "Honorários costumam ser cobrados por valor fixo (causas simples), percentual sobre o valor da causa (ações judiciais), ou contrato de êxito (cliente só paga se ganhar) — depende do caso.",
      "Documentos geralmente pedidos na primeira consulta: RG, CPF, comprovante de residência e documentos relacionados ao caso (contrato, notificação, boletim de ocorrência).",
      "Prazos processuais são regidos pela lei e pelo andamento do processo no tribunal — o escritório informa prazos específicos conforme o caso avança.",
      "Atendimento pode ser presencial ou por videochamada, dependendo da preferência do cliente.",
      "Consultas costumam durar de 30 a 60 minutos.",
      "Sigilo profissional é garantido em toda consulta — informações do cliente não são compartilhadas.",
      "Cancelamento ou remarcação de consulta deve ser avisado com pelo menos 24 horas de antecedência.",
      "Aceitamos Pix, cartão e transferência bancária; parcelamento de honorários pode ser negociado conforme o caso.",
      "Casos urgentes (prisão, medida protetiva, liminar) têm prioridade e devem ser sinalizados assim que o cliente entrar em contato.",
      "Nunca prometer resultado garantido de um processo — sempre dizer que cada caso é avaliado individualmente por um advogado.",
      "Se o cliente perguntar o valor exato de honorários sem detalhar o caso, oriente que isso só é definido após a consulta de avaliação.",
      "Atualizações sobre andamento processual são feitas diretamente pelo advogado responsável, não pelo atendimento automático.",
    ],
  },
  {
    id: "imoveis",
    nome: "Corretor de imóveis",
    descricao: "Venda, locação, imobiliária",
    baseConhecimento: [
      "Trabalhamos com venda, locação e, dependendo da equipe, administração de imóveis — informar quais serviços o negócio realmente oferece.",
      "Visitas a imóveis podem ser agendadas com antecedência mínima de algumas horas, conforme disponibilidade do corretor e do proprietário.",
      "Documentos geralmente pedidos para locação: RG, CPF, comprovante de renda (3x o valor do aluguel) e comprovante de residência; fiador ou seguro-fiança pode ser exigido.",
      "Documentos para compra: RG, CPF, comprovante de renda, e análise de crédito caso use financiamento bancário.",
      "Taxa de administração de aluguel costuma ser em torno de 8% a 10% do valor do contrato — confirmar a taxa real praticada.",
      "Comissão de venda costuma seguir a tabela do CRECI da região (geralmente 6% sobre o valor do imóvel) — confirmar a prática do escritório.",
      "Financiamento imobiliário pode ser feito pela Caixa, bancos privados ou construtora, dependendo do imóvel — o corretor orienta qual opção é mais vantajosa.",
      "Fotos, vídeo e tour virtual dos imóveis disponíveis podem ser enviados diretamente pelo WhatsApp antes da visita presencial.",
      "Reserva de imóvel (sinal) costuma ser feita quando o cliente confirma interesse, formalizando com proposta por escrito.",
      "Prazo médio de análise de proposta/documentação para locação costuma ser de 2 a 5 dias úteis.",
      "Cancelamento ou remarcação de visita deve ser avisado com pelo menos 2 horas de antecedência.",
      "Aceitamos negociação de valores dentro dos limites autorizados pelo proprietário — sempre confirmar antes de fechar qualquer condição.",
      "Nunca informar o endereço completo de um imóvel de locação sem antes confirmar interesse real e agendar visita, por questão de segurança do proprietário.",
      "Se o cliente perguntar sobre um imóvel específico do portal/anúncio, peça o código ou link do anúncio pra localizar rápido.",
    ],
  },
  {
    id: "comercio",
    nome: "Comércio / loja",
    descricao: "Varejo em geral",
    baseConhecimento: [
      "Horário de funcionamento da loja deve ser confirmado e mantido atualizado — informar corretamente pra não gerar frustração.",
      "Formas de pagamento aceitas: Pix, cartão de crédito/débito (à vista e parcelado) e dinheiro.",
      "Trocas e devoluções seguem o Código de Defesa do Consumidor: 7 dias corridos pra compras online/telefone (arrependimento) e conforme a política da loja pra compras presenciais.",
      "Produto com defeito pode ser trocado em até 30 dias (não duráveis) ou 90 dias (duráveis), conforme a lei.",
      "Entrega, quando disponível, tem prazo e taxa que variam por região — confirmar o CEP do cliente antes de informar valor e prazo.",
      "Retirada na loja costuma estar disponível para pedidos feitos pelo WhatsApp ou catálogo.",
      "Promoções e descontos sazonais devem ser confirmados como ativos antes de informar ao cliente, pra não prometer condição que já encerrou.",
      "Reserva de produto (separar sem pagamento) costuma valer por um prazo limitado, por exemplo 24 horas — confirmar a prática da loja.",
      "Estoque muda com frequência — sempre confirmar disponibilidade antes de fechar um pedido, especialmente pra itens de tamanho/cor específicos.",
      "Nota fiscal é emitida em toda venda, presencial ou pelo WhatsApp.",
      "Se o cliente perguntar sobre um produto que não está mais disponível, sugerir alternativas parecidas antes de encerrar a conversa sem solução.",
      "Pedidos por WhatsApp podem ser combinados com pagamento por link de pagamento, Pix ou na retirada/entrega.",
    ],
  },
  {
    id: "pet",
    nome: "Pet shop / veterinária",
    descricao: "Banho, tosa, consultas",
    baseConhecimento: [
      "Banho e tosa de porte pequeno custam R$ 60 a R$ 90; porte médio R$ 80 a R$ 120; porte grande R$ 100 a R$ 160 — variando por raça e tipo de pelagem.",
      "Consulta veterinária de rotina custa R$ 120 a R$ 200 e leva cerca de 30 minutos.",
      "Vacinação (V10, antirrábica, etc.) custa R$ 80 a R$ 150 por dose, dependendo da vacina.",
      "Vermifugação costuma custar R$ 40 a R$ 80.",
      "Consultas de emergência (fora do horário normal) podem ter valor diferenciado — informar se há atendimento de urgência disponível.",
      "Cirurgias (como castração) exigem avaliação prévia, exames pré-operatórios e jejum do animal — não é possível informar preço fechado sem avaliação.",
      "Hospedagem/hotel para pets costuma ser cobrada por diária, incluindo alimentação — confirmar o valor real praticado.",
      "Agendamento de banho e tosa pode ser feito com alguns dias de antecedência, especialmente em época de alta demanda (véspera de feriado).",
      "Cancelamento gratuito até 2 horas antes do horário marcado.",
      "Aceitamos Pix, cartão e dinheiro.",
      "Sempre perguntar o porte, raça e temperamento do animal antes de agendar banho/tosa, pra calcular tempo e valor corretos.",
      "Em caso de emergência (acidente, envenenamento, dificuldade respiratória), orientar o tutor a vir imediatamente ou informar se há plantão 24h.",
      "Carteira de vacinação deve ser trazida em toda consulta, quando o tutor tiver.",
      "Produtos (ração, petiscos, acessórios) também são vendidos no local, quando aplicável.",
    ],
  },
  {
    id: "academia",
    nome: "Academia / personal",
    descricao: "Treino, musculação, pilates",
    baseConhecimento: [
      "Plano mensal de academia custa a partir de R$ 100 a R$ 200, dependendo da modalidade e estrutura.",
      "Aula experimental gratuita costuma estar disponível para novos alunos — confirmar disponibilidade de horário.",
      "Personal trainer (aula individual) custa R$ 80 a R$ 150 por sessão, ou pacote mensal com desconto.",
      "Avaliação física (bioimpedância, medidas) costuma ser gratuita ou custar até R$ 50, e é recomendada antes de iniciar o treino.",
      "Modalidades comuns: musculação, funcional, pilates, spinning, crossfit — informar apenas as que a academia realmente oferece.",
      "Matrícula pode ter taxa única além da mensalidade — confirmar se há isenção em promoções.",
      "Cancelamento de plano costuma exigir aviso prévio de 30 dias, conforme contrato.",
      "Trancamento temporário do plano (por viagem, lesão, etc.) costuma ser possível mediante solicitação.",
      "Horário de pico costuma ser no início da manhã e final da tarde — informar se há restrição de horário em planos mais baratos.",
      "Aceitamos Pix, cartão (recorrência automática pra mensalidade) e boleto.",
      "Alunos devem trazer atestado médico ou liberação, dependendo da modalidade e política da academia.",
      "Se o aluno perguntar sobre resultado (emagrecimento, ganho de massa), sempre reforçar que resultado depende de frequência, alimentação e orientação do profissional — nunca prometer número exato.",
    ],
  },
  {
    id: "restaurante",
    nome: "Restaurante / delivery",
    descricao: "Comida, lanches, entregas",
    baseConhecimento: [
      "Cardápio principal e preços devem ser enviados junto com fotos quando o cliente perguntar o que o estabelecimento tem.",
      "Pedido pode ser feito para retirada no local ou entrega, dependendo da estrutura do estabelecimento.",
      "Taxa de entrega e prazo variam por região — sempre confirmar o bairro/CEP antes de informar valor e tempo estimado.",
      "Tempo médio de preparo costuma ser de 30 a 50 minutos, podendo aumentar em horário de pico (sexta e sábado à noite).",
      "Pedido mínimo para entrega, quando existir, deve ser informado antes de fechar o pedido.",
      "Formas de pagamento aceitas: Pix, cartão (na entrega ou por link) e dinheiro — informar se há troco disponível.",
      "Reservas de mesa para datas especiais devem ser feitas com antecedência, especialmente fins de semana.",
      "Restrições alimentares (vegano, sem glúten, alergias) devem ser sempre perguntadas e confirmadas com a cozinha antes de garantir ao cliente.",
      "Promoções (combo, dia da semana com desconto) devem ser confirmadas como ativas antes de informar ao cliente.",
      "Cancelamento de pedido só é possível antes de entrar em preparo — depois disso, verificar com a cozinha.",
      "Se o cliente perguntar sobre item fora do cardápio, informar que não é possível personalizar além das opções disponíveis, salvo avisos específicos do estabelecimento.",
    ],
  },
  {
    id: "servicos-gerais",
    nome: "Prestador de serviços",
    descricao: "Elétrica, hidráulica, reforma",
    baseConhecimento: [
      "Orçamento inicial costuma ser gratuito ou ter um valor de visita técnica (ex: R$ 50 a R$ 100), descontado do serviço se fechado — confirmar a política real.",
      "Serviços comuns: reparos elétricos/hidráulicos, instalação e manutenção (ar-condicionado, chuveiro, tomadas), pequenas reformas — informar apenas o que o negócio realmente atende.",
      "Visita técnica costuma ser agendada com 1 a 3 dias de antecedência, dependendo da demanda; emergências podem ter encaixe no mesmo dia com taxa adicional.",
      "Preço final do serviço só é definido após avaliação presencial, já que depende do problema encontrado — não prometer valor fechado sem visita.",
      "Emergências (vazamento grande, falta de energia, risco de segurança) têm prioridade — sempre perguntar se é urgente antes de agendar horário normal.",
      "Garantia do serviço costuma ser de 90 dias para mão de obra — confirmar o prazo real praticado.",
      "Materiais podem ser fornecidos pelo prestador (com acréscimo no valor) ou pelo próprio cliente — perguntar preferência.",
      "Aceitamos Pix, cartão e dinheiro; serviços de maior valor podem ser parcelados.",
      "Horário de atendimento padrão é comercial; atendimento fora desse horário pode ter taxa adicional — informar se disponível.",
      "Sempre pedir fotos ou vídeo do problema pelo WhatsApp antes da visita, quando possível, pra o profissional já ir preparado com material.",
    ],
  },
  {
    id: "floricultura",
    nome: "Floricultura",
    descricao: "Flores, arranjos, presentes",
    baseConhecimento: [
      "Arranjos e buquês têm preços a partir de R$ 80, variando por tamanho e tipo de flor (rosas, girassóis, flores do campo, etc.) — ajustar com a tabela real.",
      "Entrega no mesmo dia costuma estar disponível para pedidos feitos até um horário limite (ex: 15h) — confirmar o horário de corte real.",
      "Cesta de café da manhã, plantas ornamentais e presentes combinados (flor + chocolate/vinho) também costumam fazer parte do catálogo.",
      "Taxa de entrega varia por região — sempre confirmar bairro/CEP antes de informar valor e prazo.",
      "Datas de alta demanda (Dia das Mães, Dia dos Namorados, Finados) exigem pedido com mais antecedência — avisar o cliente se a data está próxima do limite.",
      "Cartão com mensagem personalizada pode ser incluído gratuitamente no arranjo/buquê.",
      "Pagamento aceito: Pix, cartão e dinheiro (na loja); pedidos por WhatsApp geralmente fecham com Pix ou link de pagamento.",
      "Substituição de flores por motivo de disponibilidade sazonal pode acontecer — sempre avisar o cliente se algo do pedido original não estiver disponível.",
      "Encomendas para eventos (casamento, formatura, decoração) exigem orçamento personalizado e prazo maior de antecedência.",
      "Cuidados básicos da flor/planta (troca de água, luz, poda) podem ser enviados junto com a entrega, se o cliente perguntar.",
      "Cancelamento de pedido só é possível antes de o arranjo entrar em produção.",
    ],
  },
  {
    id: "outro",
    nome: "Outro tipo de negócio",
    descricao: "Nenhum acima combina exatamente",
    baseConhecimento: [
      "Descreva aqui os principais produtos ou serviços que seu negócio oferece, com preço e duração aproximados.",
      "Informe as formas de pagamento aceitas (Pix, cartão, dinheiro).",
      "Explique a política de cancelamento e remarcação de horários ou pedidos.",
      "Liste as perguntas mais comuns que seus clientes fazem, com a resposta que você normalmente dá.",
      "Edite ou apague estes itens de exemplo e substitua pelas informações reais do seu negócio — quanto mais completo, melhor o robô atende.",
    ],
  },
];

export function getSegmento(id: string): Segmento | undefined {
  return SEGMENTOS.find((s) => s.id === id);
}
